### PR TITLE
improvement: first review of english to pt-br

### PR DESCRIPTION
**Pull request by joaomantovani**
# Description

First revision of PT-BR language.

Please wait my go ahead to merge, because our team will do a second review.

## Review

- [x] @joaomantovani review
- [x] @minghini review

### CODE REVIEW

**Comment by joaomantovani** [comment]
All the review are done, you can now merge on jetadmin!

**Comment by f1nality** [comment]
Hi @joaomantovani 
Thanks a lot for reviewing.

Initial PT localization was generated by Google Translate. Google Translate does not have different options for Portuguese and Brazilian Portuguese. As I understood: Google Translate uses non Brazilian Portuguese.

So the question: have you applied edits to change to Brazilian Portuguese from Portuguese or it was just edits of incorrect translation? We need to understand if we should create a separate Brazilian Portuguese based on your version or rename current Portuguese to Brazilian Portuguese?

Also have you checked if email templates are correct?

Thanks.

**Comment by joaomantovani** [comment]
Hi @f1nality 

> So the question: have you applied edits to change to Brazilian Portuguese from Portuguese or it was just edits of incorrect translation?

Answer: "just edits of incorrect translation"

> We need to understand if we should create a separate Brazilian Portuguese based on your version or rename current Portuguese to Brazilian Portuguese?

Normally, the locales has two languages: 
- pt (portugal)
- pt-BR (Brazil). 

This locale is written in pt-BR. 

If you want, the most correct is create the locale for pt-BR. The other applications around the world normally just use the term: "Portuguese" and references to Brazilian language itself, it's not the grammatically correct, but considering the amount of the population of Brazil vs Portugal is more easy to have one locale.

> Also have you checked if email templates are correct?
- [x] `locales/email/email_verification/email_verification.pt.html`
- [x] `locales/email/project_user_invitation/project_user_invitation.pt.html`
- [x] `locales/email/user_restore/user_restore.pt.html`

When reviewing again these files above, I realized that the term `Restauração (restoration)` could be exchanged by `Recuperação (recovery)`. The both are correctly, but the second term is more frequently used.

```diff
locales/email/user_restore/user_restore.pt.html

+ Restauração
- Recuperação
```

Please, feel free to ask any questions you want! 😉

**Comment by joaomantovani** [comment]
I've made a third review on locale and change three typos to be better!

**Comment by f1nality** [comment]
@joaomantovani Thanks! PR is merged and released now. Please check

**Pull request merged**
