### PR TITLE
First Korean Commit

### PR DESCRIPTION
**Pull request by hellosunghyun**

### CODE REVIEW

**Comment by f1nality** [comment]
Hi @hellosunghyun first of all - thanks a lot for translation! it looks good, but it miss Emails translations. Could you please translate them as well?
https://github.com/jet-admin/jet-localization/tree/master/locales/email

Actually there is not much text in it

**Comment by hellosunghyun** [comment]
okay, i'll check it!

**Comment by hellosunghyun** [comment]
finish!

**Comment by f1nality** [comment]
@hellosunghyun surprisingly fast! thanks a lot. we will check it more detailed to see if anything else should be fixed and plan to publish it with the next feature release.

**Comment by hellosunghyun** [comment]
Thank you! Always contact me!

**Comment by f1nality** [comment]
@hellosunghyun we haven't found any issues, only updated file code style. This is merged now, we plan to released it within 1-2 days. I will let you know. Thanks again!

**Comment by f1nality** [comment]
@hellosunghyun localization is released in 2.38.0!

**Pull request merged**
