### PR TITLE
Added English-to-Japansese translation

### PR DESCRIPTION
**Pull request by reito-hos2**
Hello @antohasvs @joaomantovani @minghini,

I hope this message finds you well. I have recently been working on a translation improvement for Jet Admin, specifically translating content from English to Japanese. I believe this addition will be beneficial for Japanese users and help widen the audience of the project.

Here's a summary of my changes:

- Added Translation of English content to Japanese in
  - locale.ja.ts
  - email/*.html
- Proofread and adjusted the translations for clarity and consistency
- Ensured all technical terms and jargon are accurately translated

Co-Authored-By: https://github.com/kobashowww

### CODE REVIEW

**Comment by f1nality** [comment]
Hello @reito-hos2 thanks a lot for your PR.

- .json file looks good
- we've noticed there are incorrect HTML {% if %} tags in verification email, maybe there are some more. Its not allowed to have {% %} tag newline inside it (example below).

We will inspect other files during integration process, but now it looks like it is almost ready for integration. We plan to add it in the upcoming update.

```
{% if domain %}https://{{domain.domain}}{%
                                  else %}{{frontend_url}}{% endif %}
```

**Comment by reito-hos2** [comment]
@antohasvs 
Thank you for your reply.

> we've noticed there are incorrect HTML {% if %} tags in verification email, maybe there are some more. Its not allowed to have {% %} tag newline inside it (example below).

⇒ Sorry! I fixed it in the latest commit.

**Comment by f1nality** [comment]
@reito-hos2 thank you!

**Comment by f1nality** [comment]
@reito-hos2 in email_verification.ja.html there is a label

```
メールアドレスの有効化
```

which was translated from

```
Hello, {{user.first_name}}!
```

but in user_restore.ja.html it is translated as 

```
{{user.first_name}}さん、こんにちは！
```

which one is correct? I think we should preserve {{user.first_name}} identically for all translations

**Comment by f1nality** [comment]
Also we found issues in locale.ja.ts translation, could you please check? (maybe they are just misplaced)

Locale "Japanese" has duplicated items: 
"is Previous Week", "previous week", "is not previous week", "{0} is previous week", "{0} is not previous week|, "is Previous Month", "previous month", "is not previous month", "{0} is previous month", "{0} is not previous month"

Locale "Japanese" has missing items: 
"is Current Week", "current week", "is not current week", "{0} is current week", "{0} is not current week", "is Current Month", "current month", "is not current month", "{0} is current month", "{0} is not current month"

**Comment by reito-hos2** [comment]
@antohasvs 
Thank you for the review.
We will fix the issues ASAP.

**Comment by reito-hos2** [comment]
I believe issues are all solved now.

**Comment by f1nality** [comment]
@reito-hos2 i think these are the last edits, missing translation in Email templates:

project_user_invitation.ja.html line 252
```
                            <td><a href="{{frontend_url}}/projects/invite/{{code}}{% if registered %}?registered=1{% endif %}" style="display: table-cell; text-decoration: none; padding: 15px 30px; font-size: 15px; text-align: center; font-weight: bold; font-family:Helvetica Neue, Helvetica, Arial, sans-serif; width: 100%;color:#ffffff; border:0px solid ; background-color:#2b50ed; border-radius: 3px;">
                              Join Now
                            </a></td>
```


user_restore.ja.html line 200
```
                        <div style="margin-right: auto; font-family: Helvetica Neue, Helvetica, Arial, sans-serif; color:#222222;font-size:26px;line-height:1.3;">
                          <strong>Password Restore</strong>
                        </div>
```

**Comment by reito-hos2** [comment]
@antohasvs 
Thank you for pointing out!
I have added missing translation, and checked the HTML preview just to make sure everything looked fine.

**Comment by f1nality** [comment]
@reito-hos2 now everything looks good, merged. Thank you for the PR! Will be available in the upcoming update

**Pull request merged**
